### ISSUE TITLE
sds_incl.h not found while compiling 

### ISSUE THREAD

**Issue by DjImene** [tkat0/pynqmmult#1]
hello! I'm working on the pynq board and I used the mmult overlay but then I wanted to recreate the project in vivado hls, the problem is that I'm having the same error all over again, it's:
 "fatala error: 'sds_incl.h' file not foud
#influde"sds_incl.h"
               ^
1 error generated.
ERROR: [HLS 200-101] mESSAGE id '1-1' value invalid for uing argument."

and a bunch of other stuff related. I've putted this file myself into the project over and over but I've got the same issue. I don't know if I'm doing something wrong, it must be so, it would be really cool if someone could lighten me please!

**Comment by leos313** [comment]
try to include it manually from [here](https://github.com/hackwa/pynqfire/blob/master/src/hardware/include/sds_incl.h)
